#!/bin/bash

#SBATCH --job-name=post_process_hybrid_powerlaw_60000_80000
#SBATCH --time=24:00:00
#SBATCH --nodes=1 
#SBATCH --ntasks-per-node=48
#SBATCH --partition=defq
#SBATCH --mail-type=ALL
#SBATCH --mail-user=vkapil1@jh.edu

ml anaconda
conda activate gwbench_dev


python ~/scratch16-berti/3G_systematics_veome/src/combine_fisher_binaries.py -i "../data/powerlaw_smooth_hybrid_3G_production" -o "../output/powerlaw_smooth_hybrid_3G_production" -N 20000 --offset 60000
    