#!/bin/bash

#SBATCH --job-name=mcmc_parallel_smooth_power_law
#SBATCH --time=20:00:00
#SBATCH --nodes=1 
#SBATCH --ntasks=48
#SBATCH --partition=defq
#SBATCH --mail-type=ALL
#SBATCH --mail-user=vkapil1@jh.edu

ml anaconda
conda activate gwbench


python ~/scratch16-berti/3G_systematics_veome/src/run_mcmc_smooth_powerlaw_numba.py --mcmc_params 0 1 2 4 5 -i "../output/powerlaw_3.5_lams_smooth" -o "../mcmc/powerlaw_3.5_smooth_sbatch" --N_MCMC 1000 --N_walkers 15  --N_parallel 48 --reset False



