#!/bin/bash

#SBATCH --job-name=grid_mtot_q
#SBATCH --time=4:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=48
#SBATCH --partition=defq
#SBATCH --mail-type=ALL
#SBATCH --mail-user=vkapil1@jh.edu

ml anaconda
conda activate gwbench

mpirun -n 48 python ~/scratch16-berti/3G_systematics_veome/src/sample_pop_from_grid_m1_q.py -N 240 --mtot=12.0 --offset 0 --DL 1000 -o ../data/mtot_q_grids/mtot_12_grid_DL_1000
