#!/bin/bash

#SBATCH --job-name=uniform_events
#SBATCH --time=3:00:00
#SBATCH --nodes=2 
#SBATCH --ntasks=48
#SBATCH --partition=defq
#SBATCH --mail-type=ALL
#SBATCH --mail-user=vkapil1@jh.edu

ml anaconda
conda activate gwbench

mpirun -n 24 python ~/scratch16-berti/3G_systematics_veome/src/sample_pop_from_uniform.py -N 192 --offset 96
mpirun -n 24 python ~/scratch16-berti/3G_systematics_veome/src/sample_pop_from_uniform.py -N 192 --offset 288


