#!/bin/bash

#SBATCH --job-name=grid_mtot_q
#SBATCH --time=4:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=40
#SBATCH --partition=defq
#SBATCH --mail-type=ALL
#SBATCH --mail-user=vkapil1@jh.edu

ml anaconda
conda activate gwbench


mpirun -n 10 python ~/scratch16-berti/3G_systematics_veome/src/sample_pop_from_grid_mtot_q.py -N 10 --offset 0 --mtot=50.0 --SNR 100.0 -o ../data/mtot_q_grids_xhm_vs_hm/mtot_50_grid_SNR_100 --approximant1 "IMRPhenomXHM" --approximant2 "IMRPhenomHM" --suffix1 "xhm" --suffix2 "hm"

mpirun -n 10 python ~/scratch16-berti/3G_systematics_veome/src/sample_pop_from_grid_mtot_q.py -N 10 --offset 0 --mtot=60.0 --SNR 100.0 -o ../data/mtot_q_grids_xhm_vs_hm/mtot_60_grid_SNR_100 --approximant1 "IMRPhenomXHM" --approximant2 "IMRPhenomHM" --suffix1 "xhm" --suffix2 "hm"

mpirun -n 10 python ~/scratch16-berti/3G_systematics_veome/src/sample_pop_from_grid_mtot_q.py -N 10 --offset 0 --mtot=70.0 --SNR 100.0 -o ../data/mtot_q_grids_xhm_vs_hm/mtot_70_grid_SNR_100 --approximant1 "IMRPhenomXHM" --approximant2 "IMRPhenomHM" --suffix1 "xhm" --suffix2 "hm"

mpirun -n 10 python ~/scratch16-berti/3G_systematics_veome/src/sample_pop_from_grid_mtot_q.py -N 10 --offset 0 --mtot=80.0 --SNR 100.0 -o ../data/mtot_q_grids_xhm_vs_hm/mtot_80_grid_SNR_100 --approximant1 "IMRPhenomXHM" --approximant2 "IMRPhenomHM" --suffix1 "xhm" --suffix2 "hm"
