#!/bin/bash

#SBATCH --job-name=hybrid_powerlaw_alpha_3.5_smooth_Voyager_hybr_0_1000
#SBATCH --time=48:00:00
#SBATCH --nodes=5 
#SBATCH --ntasks=240
#SBATCH --partition=defq
#SBATCH --mail-type=ALL
#SBATCH --mail-user=vkapil1@jh.edu

ml anaconda
conda activate gwbench_dev

mpirun -launcher fork -np 240 python ~/scratch16-berti/3G_systematics_veome/src/compute_hybrid_fisher.py -N 1000 --offset 0 -i "../data/smooth_powerlaw_pop.npz" -o "../data/powerlaw_smooth_hybrid_Voyager" --hybr 0.0 --approx1 "IMRPhenomXAS" --approx2 "IMRPhenomD"  --net_key "Voyager"

mpirun -launcher fork -np 240 python ~/scratch16-berti/3G_systematics_veome/src/compute_hybrid_fisher.py -N 1000 --offset 0 -i "../data/smooth_powerlaw_pop.npz" -o "../data/powerlaw_smooth_hybrid_Voyager" --hybr 0.5 --approx1 "IMRPhenomXAS" --approx2 "IMRPhenomD"  --net_key "Voyager"

mpirun -launcher fork -np 240 python ~/scratch16-berti/3G_systematics_veome/src/compute_hybrid_fisher.py -N 1000 --offset 0 -i "../data/smooth_powerlaw_pop.npz" -o "../data/powerlaw_smooth_hybrid_Voyager" --hybr 0.8 --approx1 "IMRPhenomXAS" --approx2 "IMRPhenomD"  --net_key "Voyager"

mpirun -launcher fork -np 240 python ~/scratch16-berti/3G_systematics_veome/src/compute_hybrid_fisher.py -N 1000 --offset 0 -i "../data/smooth_powerlaw_pop.npz" -o "../data/powerlaw_smooth_hybrid_Voyager" --hybr 0.85 --approx1 "IMRPhenomXAS" --approx2 "IMRPhenomD"  --net_key "Voyager"

mpirun -launcher fork -np 240 python ~/scratch16-berti/3G_systematics_veome/src/compute_hybrid_fisher.py -N 1000 --offset 0 -i "../data/smooth_powerlaw_pop.npz" -o "../data/powerlaw_smooth_hybrid_Voyager" --hybr 0.9 --approx1 "IMRPhenomXAS" --approx2 "IMRPhenomD"  --net_key "Voyager"

mpirun -launcher fork -np 240 python ~/scratch16-berti/3G_systematics_veome/src/compute_hybrid_fisher.py -N 1000 --offset 0 -i "../data/smooth_powerlaw_pop.npz" -o "../data/powerlaw_smooth_hybrid_Voyager" --hybr 0.95 --approx1 "IMRPhenomXAS" --approx2 "IMRPhenomD"  --net_key "Voyager"

mpirun -launcher fork -np 240 python ~/scratch16-berti/3G_systematics_veome/src/compute_hybrid_fisher.py -N 1000 --offset 0 -i "../data/smooth_powerlaw_pop.npz" -o "../data/powerlaw_smooth_hybrid_Voyager" --hybr 0.96 --approx1 "IMRPhenomXAS" --approx2 "IMRPhenomD"  --net_key "Voyager"

mpirun -launcher fork -np 240 python ~/scratch16-berti/3G_systematics_veome/src/compute_hybrid_fisher.py -N 1000 --offset 0 -i "../data/smooth_powerlaw_pop.npz" -o "../data/powerlaw_smooth_hybrid_Voyager" --hybr 0.97 --approx1 "IMRPhenomXAS" --approx2 "IMRPhenomD"  --net_key "Voyager"

mpirun -launcher fork -np 240 python ~/scratch16-berti/3G_systematics_veome/src/compute_hybrid_fisher.py -N 1000 --offset 0 -i "../data/smooth_powerlaw_pop.npz" -o "../data/powerlaw_smooth_hybrid_Voyager" --hybr 0.98 --approx1 "IMRPhenomXAS" --approx2 "IMRPhenomD"  --net_key "Voyager"

mpirun -launcher fork -np 240 python ~/scratch16-berti/3G_systematics_veome/src/compute_hybrid_fisher.py -N 1000 --offset 0 -i "../data/smooth_powerlaw_pop.npz" -o "../data/powerlaw_smooth_hybrid_Voyager" --hybr 0.99 --approx1 "IMRPhenomXAS" --approx2 "IMRPhenomD"  --net_key "Voyager"

mpirun -launcher fork -np 240 python ~/scratch16-berti/3G_systematics_veome/src/compute_hybrid_fisher.py -N 1000 --offset 0 -i "../data/smooth_powerlaw_pop.npz" -o "../data/powerlaw_smooth_hybrid_Voyager" --hybr 1.0 --approx1 "IMRPhenomXAS" --approx2 "IMRPhenomD"  --net_key "Voyager"



